# SPDX-License-Identifier: CC0-1.0
name: Build and deploy aports
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/buildrepo.yml
      - 'apk/keys/**'
      - 'aports/user-test/**'
  pull_request:
    paths:
      - .github/workflows/buildrepo.yml
      - 'apk/keys/**'
      - 'aports/user-test/**'
  workflow_dispatch:

env:
  ALPINE_BRANCH: v3.24

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    container: alpine:3.24
    steps:
      # note: we can't use some actions on alpine arm64 alas
      # https://github.com/actions/runner/issues/801
      - name: Configure apk build environemnt
        run: |
          echo ::group::Install dependencies
          apk add -U \
            alpine-sdk \
            lua-aports \
            rclone \
            su-exec
          echo ::endgroup::

          echo ::group::Checkout manually
          wget "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/tarball/$GITHUB_SHA" --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -O - | tar zxvf - --strip-components 1
          echo ::endgroup::

          echo ::group::Create user for abuild
          adduser -D smith
          addgroup smith abuild
          echo ::endgroup::

          echo ::group::Configure abuild
          su-exec smith mkdir -vp /home/smith/.abuild/
          su-exec smith install -vDm644 apk/keys/*.pub /home/smith/.abuild/
          keyname=$(find /home/smith/.abuild/ -type f -name '*.pub' -exec basename {} .pub \;)
          su-exec smith sh -c "printf '%s' '${{ secrets.abuild_priv_key }}' > /home/smith/.abuild/$keyname"
          su-exec smith sh -c "printf 'PACKAGER_PRIVKEY=\"/home/smith/.abuild/%s\"\n' \"$keyname\" | tee -a /home/smith/.abuild/abuild.conf"
          echo ::endgroup::

          echo ::group::Initialize apk repository
          install -vm 644 apk/keys/*.pub /etc/apk/keys/
          echo /home/smith/packages/user-test | tee -a /etc/apk/repositories
          echo ::endgroup::

      - name: Download packages from R2
        run: |
          echo ::group::Configure rclone for R2
          # setup rclone
          su-exec smith mkdir -vp /home/smith/.config/rclone/
          cat << 'EOS' | su-exec smith tee /home/smith/.config/rclone/rclone.conf >/dev/null
          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.r2_access_key_id }}
          secret_access_key = ${{ secrets.r2_secret_access_key }}
          endpoint = ${{ secrets.r2_endpoint }}
          acl = private
          no_check_bucket = true
          EOS
          echo ::endgroup::

          echo ::group::Run rclone
          su-exec smith mkdir -vp /home/smith/packages/
          su-exec smith rclone copy -v r2:alpine-test-chamber/"$ALPINE_BRANCH"/user-test/"$(abuild -A)"/ /home/smith/packages/user-test/"$(abuild -A)"/
          echo ::endgroup::

      - name: Build aports
        run: |
          echo ::group::Run buildrepo
          chown -vR smith:smith "$(pwd)"/aports
          su-exec smith buildrepo -a "$(pwd)"/aports user-test
          echo ::endgroup::

      - name: Upload packages to R2
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo ::group::Run rclone sync
          su-exec smith rclone sync -v /home/smith/packages/user-test/"$(abuild -A)"/ r2:alpine-test-chamber/"$ALPINE_BRANCH"/user-test/"$(abuild -A)"/
          echo ::endgroup::
