# SPDX-License-Identifier: CC0-1.0
name: Run ltp
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '30 18 * * 4'
  workflow_dispatch:

env:
  ALPINE_BRANCH: v3.23

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        suite:
          - syscalls
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - name: Create VM image
        run: |
          wget -q https://raw.githubusercontent.com/alpinelinux/alpine-make-vm-image/v0.13.4/alpine-make-vm-image \
            && echo '03dc4581b1eaa34a951cc210e963b98ded44dc469f7d0c05f00431ceb58390b78f3db0386fc94aa1e5b2c6471f2dd74b663454179781bdd3a30776ffa525e2cb  alpine-make-vm-image' | sha512sum -c \
            || exit 1

          echo ::group::Install dependencies
          arch="$(uname -m)"
          case "$arch" in
            x86_64) qemu_arch=x86;;
            aarch64) qemu_arch=arm;;
          esac
          sudo apt-get update
          sudo apt-get install qemu-utils qemu-system-"$qemu_arch" python3-pip
          sudo pip install kirk
          echo ::endgroup::

          echo ::group::Create Alpine VM image
          sed \
            -e "s/@ALPINE_BRANCH@/$ALPINE_BRANCH/" \
            -e 's|@R2_DEV_URL@|${{ secrets.r2_dev_url }}|' \
            apk/repositories.in > apk/repositories
          sed -i \
            -e "s/'ttyS0'/'hvc0'/" \
            -e "s/'console=tty0'/'console=hvc0'/" \
            alpine-make-vm-image
          sudo sh ./alpine-make-vm-image \
            --image-format qcow2 \
            --image-size 8G \
            --keys-dir apk/keys/"$arch" \
            --repositories-file apk/repositories \
            --packages ltp \
            --script-chroot \
            --serial-console \
            alpine-vm.qcow2 -- ./configure.sh
          echo ::endgroup::

      # https://github.blog/changelog/2024-04-02-github-actions-hardware-accelerated-android-virtualization-now-available/
      - name: Enable KVM group perms
        if: ${{ runner.arch == 'X64' }}
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run test on QEMU
        run: |
          arch="$(uname -m)"
          if [ "$arch" = aarch64 ]; then
            machine=virt
            cpu=cortex-a76
            uefi_code=/usr/share/AAVMF/AAVMF_CODE.fd
            uefi_vars=/usr/share/AAVMF/AAVMF_VARS.fd
            options="-machine $machine -cpu $cpu -drive if=pflash,format=raw,readonly=on,file=$uefi_code -drive if=pflash,format=raw,file=$uefi_vars"

            sudo sed -i \
              -e '/"-enable-kvm"/d' \
              -e 's|/dev/vport1p1|/dev/vport2p1|' \
              "$(python -c 'import libkirk; print(libkirk.__path__[0])')"/channels/qemu.py
          fi

          echo ::group::Run ltp
          sudo LTP_TIMEOUT_MUL=8 kirk \
            --verbose \
            --com "qemu:image=alpine-vm.qcow2:user=root:system=$arch:ram=3G:smp=$(nproc):serial=virtio${options:+:options=$options}" \
            --sut default:com=qemu \
            --suite-timeout 2h \
            --run-suite ${{ matrix.suite }}
          echo ::endgroup::
